import streamlit as st
import requests
import datetime

# from exception.exceptions import TradingBotException
import sys

BASE_URL = "http://localhost:8000"  # Backend endpoint

st.set_page_config(
    page_title="Travel Planner Agentic Application",
    page_icon="🌍",
    layout="centered",
    initial_sidebar_state="expanded",
)

st.title("🌍 Travel Planner Agentic Application")

# Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display chat history
st.header("How can I help you in planning a trip? Let me know where do you want to visit.")

# Chat input box at bottom
with st.form(key="query_form", clear_on_submit=True):
    user_input = st.text_input("User Input", placeholder="e.g. Plan a trip to Goa for 5 days")
    col1, _, col2 = st.columns([1, 4, 1])
    with col1:
        submit_button = st.form_submit_button("Send")
    with col2:
        download_button = st.form_submit_button("Download")

if submit_button and user_input.strip():
    try:
        # # Show user message
        # Show thinking spinner while backend processes
        with st.spinner("Bot is thinking..."):
            payload = {"question": user_input}
            response = requests.post(f"{BASE_URL}/query", json=payload)

        if response.status_code == 200:
            answer = response.json().get("answer", "No answer returned.")
            markdown_content = f"""# 🌍 AI Travel Plan

            # **Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
            # **Created by:** Atriyo's Travel Agent

            ---

            {answer}

            ---

            *This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
            """
            st.markdown(markdown_content)
            st.session_state["answer"] = answer

        else:
            st.error(" Bot failed to respond: " + response.text)

    except Exception as e:
       st.error(f"Backend server error: {e}")
       st.stop()


# Handle download request
if download_button and "answer" in st.session_state:
    with st.spinner("Preparing your travel plan for download..."):
        response = requests.post(
            f"{BASE_URL}/download",
            json={"answer": st.session_state["answer"]}
        )

        st.download_button(
            label="Download Travel Plan (PDF)",
            data=response.content,
            file_name="travel_plan.pdf",
            mime="application/pdf"
        )
st.sidebar.title("map and weather config")  
weather_api_key = st.sidebar.text_input(f"weather_API Key", value="", key=f"weather_api_key", type="password")
gplaces_api_key = st.sidebar.text_input(f"Gplaces_API Key", value="", key=f"Gplaces_api_key", type="password")
four_quare_api_key = st.sidebar.text_input(f"four_squre_API Key", value="", key=f"four_square_api_key", type="password")


st.sidebar.title("⚙️LLM Config")
provider = st.sidebar.radio(
    "Select LLM Provider",
    ["Groq", "OpenAI"]
)

api_key = st.sidebar.text_input(f"{provider} API Key", value="", key=f"{provider}_api_key", type="password")

if provider and api_key:
    if provider == "OpenAI":
        model = st.sidebar.selectbox("Select OpenAI Model", ["gpt-3.5-turbo", "gpt-4"], index=0)
        st.sidebar.success(f"Configured {provider} with model {model}")
    elif provider == "Groq":
        model = st.sidebar.selectbox("Select Groq Model", ["groq-3.5-turbo", "groq-4", "llama-3.3-70b-versatile"], index=0) 
        st.sidebar.success(f"Configured {provider} with model {model}")

    if st.sidebar.button("Save Config"):
        try:
            response = requests.post(
                "http://127.0.0.1:8000/set_llm_config",  # FastAPI URL
                json={
                    "weather_api_key": weather_api_key,
                    "gplaces_api_key": gplaces_api_key,
                    "four_quare_api_key": four_quare_api_key,
                    "provider": provider,
                    "api_key": api_key,
                    "model": model
                }
            )
            if response.status_code == 200:
                st.sidebar.success(f"Config saved for {provider} with model {model}")
            else:
                st.sidebar.error("Failed to save config")
        except Exception as e:
            st.sidebar.error(f"Error: {e}")

else:
    st.sidebar.warning("Please select at least one LLM provider and enter the API key.")          