import os
import datetime
from logger import logging
from exception import MyException
from markdown_pdf import MarkdownPdf, Section

def save_document(response_text: str, directory="./output"):
    os.makedirs(directory, exist_ok=True)

    timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    filename = f"{directory}/AI_Trip_Planner_{timestamp}.pdf"
    
    # Correct usage: add_section then save
    try:
        pdf = MarkdownPdf(toc_level=2)
        content = f"""# 🌍 AI Travel Plan

**Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
**Created by:** Atriyo's Travel Agent

---

{response_text}

---

## Disclaimer

This travel plan was generated by AI. Please verify all information before travel.
"""
        pdf.add_section(Section(content))
        pdf.save(filename)  
    except Exception as e:
        logging.error(f"Error saving document: {e}")
        raise MyException("Error saving document", str(e))
   
    logging.info(f"Document saved successfully: {filename}")   
    return filename