import os
import datetime
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch

# import os
# import markdown
# from weasyprint import HTML

# def save_document(response_text: str, directory="./output"):
#     os.makedirs(directory, exist_ok=True)
#     filename = f"{directory}/travel_plan.pdf"

#     html = markdown.markdown(response_text)
#     HTML(string=html).write_pdf(filename)

#     return filename



def save_document(response_text: str, directory: str = "./output"):
    os.makedirs(directory, exist_ok=True)

    timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    filename = f"{directory}/AI_Trip_Planner_{timestamp}.pdf"

    try:
        pdf = canvas.Canvas(filename, pagesize=A4)
        width, height = A4

        x_margin = 40
        y = height - 50

        def new_page():
            nonlocal y
            pdf.showPage()
            y = height - 50

        def draw_text(text, size=10, bold=False, italic=False, indent=0):
            nonlocal y
            if y < 50:
                new_page()

            font = "Helvetica"
            if bold:
                font = "Helvetica-Bold"
            if italic:
                font = "Helvetica-Oblique"

            pdf.setFont(font, size)
            pdf.drawString(x_margin + indent, y, text)
            y -= size + 6

        # -------- Header --------
        draw_text("🌍 AI Travel Plan", size=18, bold=True)
        draw_text(f"Generated: {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}", italic=True)
        draw_text("Created by: Atriyo's Travel Agent", italic=True)
        draw_text("-" * 90)

        # -------- Markdown Parsing --------
        for line in response_text.split("\n"):
            line = line.strip()

            if not line:
                y -= 8
                continue

            if line.startswith("#### "):
                draw_text(line[5:], size=11, bold=True)

            elif line.startswith("### "):
                draw_text(line[4:], size=13, bold=True)

            elif line.startswith("## "):
                draw_text(line[3:], size=15, bold=True)

            elif line.startswith("# "):
                draw_text(line[2:], size=18, bold=True)

            elif line.startswith("- "):
                draw_text("• " + line[2:], indent=15)

            elif line.startswith("---"):
                draw_text("-" * 90)

            else:
                draw_text(line)

        # -------- Footer --------
        y -= 10
        draw_text("-" * 90)
        draw_text(
            "This travel plan was generated by AI. Please verify all information before your trip.",
            italic=True
        )

        pdf.save()
        return filename

    except Exception as e:
        print(f"PDF generation error: {e}")
        return None
